### ISSUE TITLE
Debug canbus/SPI setup in /boot/firmware/config.txt. RP1 support problem with Ubuntu Server?

### ISSUE THREAD

**Issue by danzimmerman** [danzimmerman/dz_rpi_config#1]
Thought to be closed by https://github.com/danzimmerman/dz_rpi_config/commit/13fe295029373262766fa7f58cfeabf76565c13d, but needs debugging.

Leaving it manual for now

**Comment by danzimmerman** [comment]
Tried [this](https://raspberrypi.stackexchange.com/a/94468/92623) to decrease SPI frequency and add `-overlay` to the MCP2515. Didn't work.

**Comment by danzimmerman** [comment]
Look into parsing loaded overlays and what should be there for CAN: 

https://forums.raspberrypi.com/viewtopic.php?t=336527#p2014109

**Comment by zimmerman-pliant** [comment]
try 250k freq, bcm2835 not needed, readme is right

**Comment by danzimmerman** [comment]
Try "speed" not "spimaxfrequency"

```
dtoverlay=mcp2515,spi0-0,oscillator=16000000,speed=250000
```

**Comment by danzimmerman** [comment]
Didn't work with either CAN chip.

**Comment by danzimmerman** [comment]
See here re new I/O https://www.raspberrypi.com/news/rp1-the-silicon-controlling-raspberry-pi-5-i-o-designed-here-at-raspberry-pi/

**Comment by danzimmerman** [comment]
Should try raspbian https://forums.raspberrypi.com/viewtopic.php?t=367944

**Comment by danzimmerman** [comment]
Yeah looks like maybe the RP1 I/O is getting upstreamed now: 

https://www.phoronix.com/news/Raspberry-Pi-5-RP1-Linux-RFC

**Comment by danzimmerman** [comment]
https://forums.raspberrypi.com/viewtopic.php?t=357292

**Comment by danzimmerman** [comment]
Newer article on the upstreaming of RP1 support: https://www.phoronix.com/news/Raspberry-Pi-RP1-Linux-Patches

> This patchset is an attempt to provide a minimum infrastructure to allow the RP1 chipset to be discovered and perpherals it contains to be added from a devictree overlay loaded during RP1 PCI endpoint enumeration. Followup patches should add support for the several peripherals contained in RP1.

Ubuntu Server for the Pi 5 is not using the mainline kernel I believe, but it may be that support is still complicated.

Other possible resources:

https://forums.raspberrypi.com/viewtopic.php?t=365275

https://bugs.launchpad.net/ubuntu/+source/linux-raspi

**Comment by danzimmerman** [comment]
Raspbian works fine:

```
dan@meitner:~ $ sudo dmesg | grep spi0
[    2.642716] mcp251x spi0.1 can0: MCP2515 successfully initialized.
[    2.660117] mcp251x spi0.0 can1: MCP2515 successfully initialized.
```

**Comment by danzimmerman** [comment]
Linux version info

```
dan@<computer>:~/dz_rpi_config $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
dan@<computer>:~/dz_rpi_config $ uname -a
Linux <computer> 6.6.31+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux
```

**Comment by danzimmerman** [comment]
Interestingly only on the 6.6.31 kernel here?

**Comment by danzimmerman** [comment]
I'm going to call this closed. Waiting on RP1 support in the mainline kernel, I think.

Will have to build ROS 2 from source for now.
